<?php
//    AlertTweets.php
//
//    arpsc_tweets displays the mi_arpsc twitter timeline inside
//    a normal mi-arpsc frame.  The timeline is generated by some
//    javascript provided by twitter.
//
    include('includes/session.inc');
    $title=_('Homeland Security Alerts');

    include('includes/functions.inc');

function tweets( $provider, $background, $color, $links, $height, $tback, $tfore, $providername )
{
  echo "     <p>&nbsp;</p><h1>" . $providername . "</h1>\n";
  echo "      <script src=\"http://widgets.twimg.com/j/2/widget.js\"></script>\n";
  echo "      <script>\n";
  echo "      new TWTR.Widget({\n";
  echo "	version: 2,\n";
  echo "	type: 'profile',\n";
  echo "	rpp: 8,\n";
  echo "	interval: 3000,\n";
  echo "        title: '" . $providername . "',\n";
  echo "        subject: '" . $provider . "',\n";
  echo "	width: 450,\n";
  echo "	height: $height,\n";
  echo "      theme: {\n";
  echo "	shell: {\n";
  echo "	  background: '" . $tback . "',\n";
  echo "	  color: '" . $tfore . "'\n";
  echo "	   },\n";
  echo "	   tweets: {\n";
  echo "	   background: '" . $background . "',\n";
  echo "	   color: '" . $color . "',\n";
  echo "	   links: '" . $links . "'\n";
  echo "	   }\n";
  echo "	 },\n";
  echo "       features: {\n";
  echo "	scrollbar: false,\n";
  echo "	loop: true,\n";
  echo "	live: true,\n";
  echo "	hashtags: true,\n";
  echo "	timestamp: true,\n";
  echo "	avatars: true,\n";
  echo "	behavior: 'all'\n";
  echo "       }\n";
  echo "    }).render().setUser('" . $provider . "').start();\n";
  echo "      </script>\n";
}

    // Remember the launch time
    $starttime = strftime("%A, %B %d %Y, %H:%M");

    // Open the database
    $db = mysql_connect($host , $dbuser, $dbpassword);
    mysql_select_db($DatabaseName,$db);

    ARESheader($title,"ARES RACES ARPSC Michigan Section Twitter");

    ARESleftBar( $db );
?>
  <div id="main">
<center>
    <h1>Homeland Security Alerts</h1>

<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'list',
  rpp: 1,
  interval: 6000,
  title: 'NTASAlerts',
  subject: 'Recent DHS Alerts',
  width: 450,
  height: 100,
  theme: {
    shell: {
      background: '#000080',
      color: '#ffffff'
    },
    tweets: {
      background: '#600000',
      color: '#ffffff',
      links: '#ccccff'
    }
  },
  features: {
    scrollbar: true,
    loop: false,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: true,
    behavior: 'all'
  }
}).render().setList('NTASAlerts', '').start();
</script>
<?php
      tweets('MichEMHS',
	     '#eeeeee','black','navy', 300, 'navy', 'yellow',
	     'MSP EMHSD' );
      tweets('ReadydotGov',
	     'white','black','firebrick',200,'#77ccee','#880000', 
	     'Ready dot gov');
      tweets('Citizen_Corps',
	     '#dddddd','navy','blue',200,'red','white', 
	     'Citizen Corps');
      tweets('CentUS_ShakeOut', 
	     'white', 'black', 'navy', 200, 'black', '#ff7777', 
	     'ShakeOut' );

?>
      </center>
<hr />
<!--
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 6000,
  width: 250,
  height: 300,
  theme: {
    shell: {
      background: '#333333',
      color: '#ffffff'
    },
    tweets: {
      background: '#000000',
      color: '#ffffff',
      links: '#4aed05'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: false,
    hashtags: true,
    timestamp: true,
    avatars: false,
    behavior: 'all'
  }
}).render().setUser('NTASAlerts').start();
</script>

<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 6000,
  width: 250,
  height: 300,
  theme: {
    shell: {
      background: '#333333',
      color: '#ffffff'
    },
    tweets: {
      background: '#000000',
      color: '#ffffff',
      links: '#4aed05'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: false,
    hashtags: true,
    timestamp: true,
    avatars: false,
    behavior: 'all'
  }
}).render().setUser('wb8rcr').start();
</script>
-->
<hr />

  </div>
<?php
    sectLeaders($db);
    footer($starttime,$maxdate,
      "\$Revision: 1.1 $ - \$Date: 2011-04-25 08:57:14-05 $");
?>
</div>
</body>
</html>
