<?php
//    arpsc_tweets.php
//
//    arpsc_tweets displays the mi_arpsc twitter timeline inside
//    a normal mi-arpsc frame.  The timeline is generated by some
//    javascript provided by twitter.
//
    include('includes/session.inc');
    $title=_('Michigan Section ARES/RACES');

    include('includes/functions.inc');

    // Remember the launch time
    $starttime = strftime("%A, %B %d %Y, %H:%M");

    // Open the database
    $db = mysql_connect($host , $dbuser, $dbpassword);
    mysql_select_db($DatabaseName,$db);

    ARESheader($title,"ARES RACES ARPSC Michigan Section Twitter");

    ARESleftBar( $db );
?>
  <div id="main">
<center>
    <h1>NTAS Alerts</h1>
      <p>&nbsp;</p>

      <script src="http://widgets.twimg.com/j/2/widget.js"></script>
      <script>
      new TWTR.Widget({
	version: 2,
	type: 'profile',
	rpp: 8,
	interval: 6000,
	title: 'Michigan State Police',
	subject: 'EMHSD',
	width: 400,
	height: 50,
      theme: {
	shell: {
	  background: '#000077',
	  color: '#ffff00'
	   },
	   tweets: {
	   background: '#600000',
	   color: '#ffffff',
	   links: '#66ccff'
	   }
	 },
       features: {
	scrollbar: false,
	loop: false,
	live: true,
	hashtags: true,
	timestamp: true,
	avatars: true,
	behavior: 'all'
       }
    }).render().setUser('MichEMHS').start();
      </script>
      <p>&nbsp;</p>
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'list',
  rpp: 1,
  interval: 6000,
  title: 'NTASAlerts',
  subject: 'Recent DHS Alerts',
  width: 400,
  height: 100,
  theme: {
    shell: {
      background: '#000080',
      color: '#ffffff'
    },
    tweets: {
      background: '#600000',
      color: '#ffffff',
      links: '#ccccff'
    }
  },
  features: {
    scrollbar: true,
    loop: false,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: true,
    behavior: 'all'
  }
}).render().setList('NTASAlerts', '').start();
</script>

      </center>

  </div>
<?php
    sectLeaders($db);
    footer($starttime,$maxdate,
      "\$Revision: 1.2 $ - \$Date: 2011-01-03 09:37:14-05 $");
?>
</div>
</body>
</html>
