<?php
  /*! \file counties.php

\brief A list of counties in Michigan

counties.php includes two arrays.  $cnames contains the name
of each county in Michigan.  $ccodes contains the corresponding
four character county codes for database lookup.

The "counties" include each of the seven districts as well as
the four NWS offices and an entry for Section officials.
  */

  //! Array of county names
$cnames = array (
    "Alcona",
    "Alger",
    "Allegan",
    "Alpena",
    "Antrim",
    "Arenac",
    "Baraga",
    "Barry",
    "Bay",
    "Benzie",
    "Berrien",
    "Branch",
    "Calhoun",
    "Cass",
    "Charlevoix",
    "Cheboygan",
    "Chippewa",
    "Clare",
    "Clinton",
    "Crawford",
    "Delta",
    "Dickinson",
    "Eaton",
    "Emmet",
    "Genesee",
    "Gladwin",
    "Gogebic",
    "Grand Traverse",
    "Gratiot",
    "Hillsdale",
    "Houghton",
    "Huron",
    "Ingham",
    "Ionia",
    "Iosco",
    "Iron",
    "Isabella",
    "Jackson",
    "Kalamazoo",
    "Kalkaska",
    "Kent",
    "Keweenaw",
    "Lake",
    "Lapeer",
    "Leelanau",
    "Lenawee",
    "Livingston",
    "Luce",
    "Mackinac",
    "Macomb",
    "Manistee",
    "Marquette",
    "Mason",
    "Mecosta",
    "Menominee",
    "Midland",
    "Missaukee",
    "Monroe",
    "Montcalm",
    "Montmorency",
    "Muskegon",
    "Newaygo",
    "Oakland",
    "Oceana",
    "Ogemaw",
    "Ontonagon",
    "Osceola",
    "Oscoda",
    "Otsego",
    "Ottawa",
    "Presque Isle",
    "Roscommon",
    "Saginaw",
    "Saint Clair",
    "Saint Joseph",
    "Sanilac",
    "Schoolcraft",
    "Shiawassee",
    "Tuscola",
    "Van Buren",
    "Washtenaw",
    "Wayne",
    "Wexford",
    "D1",
    "D2",
    "D3",
    "D5",
    "D6",
    "D7",
    "D8",
    "NWS-MQT",
    "NWS-DTX",
    "NWS-GRR",
    "NWS-APX",
    "Section");


//! Array of county codes
$ccodes = array (
    "ALCO",
    "ALGE",
    "ALLE",
    "ALPE",
    "ANTR",
    "AREN",
    "BARA",
    "BARR",
    "BAY", 
    "BENZ",
    "BERR",
    "BRAN",
    "CALH",
    "CASS",
    "CHAR",
    "CHEB",
    "CHIP",
    "CLAR",
    "CLIN",
    "CRAW",
    "DELT",
    "DICK",
    "EATO",
    "EMME",
    "GENE",
    "GLAD",
    "GOGE",
    "GRAN",
    "GRAT",
    "HILL",
    "HOUG",
    "HURO",
    "INGH",
    "IONI",
    "IOSC",
    "IRON",
    "ISAB",
    "JACK",
    "KZOO",
    "KALK",
    "KENT",
    "KEWE",
    "LAKE",
    "LAPE",
    "LEEL",
    "LENA",
    "LIVI",
    "LUCE",
    "MACK",
    "MACO",
    "MANI",
    "MARQ",
    "MASO",
    "MECO",
    "MENO",
    "MIDL",
    "MISS",
    "MONR",
    "MONT",
    "MTMO",
    "MUSK",
    "NEWA",
    "OAKL",
    "OCEA",
    "OGEM",
    "ONTO",
    "OSCE",
    "OSCO",
    "OTSE",
    "OTTA",
    "PRES",
    "ROSC",
    "SAGI",
    "STCL",
    "STJO",
    "SANI",
    "SCHO",
    "SHIA",
    "TUSC",
    "VANB",
    "WASH",
    "WAYN",
    "WEXF",
    "D1",  
    "D2",  
    "D3",  
    "D5",  
    "D6",  
    "D7",  
    "D8",  
    "MQT", 
    "DTX", 
    "GRR", 
    "APX",
    "Sect" );
?>