<?php

function sectLeaders()
{
?>
<td id="sidebar-right">
<div class="block block-block" id="block-block-2">
<h2 class="title">Contact Section Leaders</h2>
<div class="content"><p><strong>Section Manager</strong><br />
Dale R. Williams, WA8EFK<br />
291 Outer Dr<br />
Dundee, MI 48131-1014<br />
734-529-3232, <a href="mailto:wa8efk@arrl.org">wa8efk@arrl.org</a></p>
<p><strong>Assistant Section Manager - Administration</strong><br />
Roger D Edwards, WB8WJV<br />
709 S Almer St<br />
Caro, MI 48723-1812<br />
989-673-5722, <a href="mailto:wb8wjv@arrl.net">wb8wjv@arrl.net</a></p>
<p><strong>Special Projects</strong><br />
John T Freeman, N8ZE<br />
333 Jefferson St<br />
Sterling, MI 48659-9547<br />
989-654-2471, <a href="mailto:n8ze@arrl.net">n8ze@arrl.net</a></p>
<p><strong>Affiliated Club Coordinator</strong><br />
Daniel M Romanchik, KB6NU<br />
1325 Orkney Dr<br />
Ann Arbor, MI 48103-2966<br />
734-930-6564, <a href="mailto:kb6nu@w8pgw.org">kb6nu@w8pgw.org</a></p>
<p><strong>Official Observer Coordinator</strong><br />
Donald G Sefcik, N8NJE<br />
4486 American Heritage Rd<br />
Grand Blanc, MI 48439-7709<br />
810-694-3823, <a href="mailto:<br />
n8nje@arrl.net">n8nje@arrl.net</a></p>
<p><strong>Public Information Coordinator</strong><br />
Bobby Corr, N8CY<br />
2205 Michele Ct.<br />
Troy, MI 48085-3826<br />
248-346-2733, <a href="mailto:<br />
n8cy@gmarc.org">n8cy@gmarc.org</a></p>
<p><strong>Section Emergency Coordinator</strong><br />
John J Mc Donough, WB8RCR<br />
2211 Laurel Ln<br />
Midland, MI 48642-3820<br />
989-631-0178, 989-430-4855, <a href="mailto:<br />
wb8rcr@arrl.net">wb8rcr@arrl.net</a></p>
<p><strong>State Government Liaison</strong><br />
Edward L Hude, WA8QJE<br />
114 S College Rd<br />
Mason, MI 48854-9786<br />
<a href="mailto:wa8qje@arrl.net">wa8qje@arrl.net</a></p>
<p><strong>Section Traffic Manager</strong><br />
John J Mc Donough, WB8RCR<br />
2211 Laurel Ln<br />
Midland, MI 48642-3820<br />
989-631-0178, 989-430-4855, <a href="mailto:<br />
wb8rcr@arrl.net">wb8rcr@arrl.net</a></p>
<p><strong>Technical Coordinator</strong><br />
W Wallace Murray, KE8HR<br />
1403 S Hill Rd<br />
Milford, MI 48381-2854<br />
<a href="mailto:ke8hr@arrl.net">ke8hr@arrl.net</a></p>
</div>
 </div>
    </td>
<?php
}
?>
